// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using profileAPi.Data;

#nullable disable

namespace profileAPi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231116135518_sextaMigracion")]
    partial class sextaMigracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("profileAPi.Models.Framework", b =>
                {
                    b.Property<string>("FrameworkName")
                        .HasColumnType("TEXT");

                    b.Property<string>("FrameworkDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IsLearned")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileName")
                        .HasColumnType("TEXT");

                    b.HasKey("FrameworkName");

                    b.HasIndex("ProfileName");

                    b.ToTable("FrameworkData");
                });

            modelBuilder.Entity("profileAPi.Models.Hobby", b =>
                {
                    b.Property<string>("HobbyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileName")
                        .HasColumnType("TEXT");

                    b.HasKey("HobbyName");

                    b.HasIndex("ProfileName");

                    b.ToTable("HobbyData");
                });

            modelBuilder.Entity("profileAPi.Models.Profile", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("ProfileData");
                });

            modelBuilder.Entity("profileAPi.Models.Framework", b =>
                {
                    b.HasOne("profileAPi.Models.Profile", null)
                        .WithMany("Frameworks")
                        .HasForeignKey("ProfileName");
                });

            modelBuilder.Entity("profileAPi.Models.Hobby", b =>
                {
                    b.HasOne("profileAPi.Models.Profile", null)
                        .WithMany("Hobbies")
                        .HasForeignKey("ProfileName");
                });

            modelBuilder.Entity("profileAPi.Models.Profile", b =>
                {
                    b.Navigation("Frameworks");

                    b.Navigation("Hobbies");
                });
#pragma warning restore 612, 618
        }
    }
}
